# Generated by Django 5.1.1 on 2024-10-15 11:25

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("address", models.CharField(max_length=100, verbose_name="Адрес")),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, unique=True, verbose_name="Номер телефона"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="Электронная почта")),
                ("working_hours", models.CharField(blank=True, max_length=50, null=True, verbose_name="Часы работы")),
                ("working_days", models.CharField(blank=True, max_length=150, null=True, verbose_name="Рабочие дни")),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
        migrations.CreateModel(
            name="Expert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=35, verbose_name="Имя")),
                ("surname", models.CharField(max_length=35, verbose_name="Фамилия")),
                ("patronymic", models.CharField(blank=True, max_length=35, null=True, verbose_name="Отчество")),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None, verbose_name="Номер телефона"
                    ),
                ),
                ("job_title", models.CharField(blank=True, max_length=50, verbose_name="Должность")),
                ("responsibilities", models.CharField(blank=True, max_length=100, verbose_name="Обязанности")),
                ("description", models.TextField(blank=True, verbose_name="Информация о специалисте")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="agents/experts/", verbose_name="Фотография"),
                ),
            ],
            options={
                "verbose_name": "Специалист",
                "verbose_name_plural": "Специалисты",
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=100, verbose_name="Название")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="agents/partners/", verbose_name="Логотип"),
                ),
                ("url", models.URLField(verbose_name="Ссылка")),
            ],
            options={
                "verbose_name": "Партнер",
                "verbose_name_plural": "Партнеры",
            },
        ),
    ]
