# Generated by Django 5.1.1 on 2024-10-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sun_projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sunprojects",
            name="collected_sum",
            field=models.PositiveIntegerField(default=0, verbose_name="Собранная сумма"),
        ),
        migrations.AddField(
            model_name="sunprojects",
            name="need_sum",
            field=models.PositiveIntegerField(default=0, verbose_name="Требуемая сумма"),
        ),
    ]
