# Generated by Django 5.1.1 on 2024-10-15 11:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BankRequisites",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("inn", models.PositiveIntegerField(verbose_name="ИНН")),
                ("ogrn_ogrnip", models.PositiveIntegerField(verbose_name="ОГРН/ОГРИП")),
                ("number_account", models.PositiveIntegerField(verbose_name="Расчетный счет")),
                ("banks_name", models.CharField(max_length=450, verbose_name="Название банка")),
                ("сorr_acc", models.PositiveIntegerField(verbose_name="Корреспондентский счет банка")),
                ("bic", models.PositiveIntegerField(verbose_name="Банковский идентификационный код")),
                ("kpp", models.PositiveIntegerField(verbose_name="КПП банка")),
                ("address", models.CharField(verbose_name="Юридический адрес")),
            ],
            options={
                "verbose_name": "Реквизиты",
                "verbose_name_plural": "Реквизиты",
                "db_table": "requisites",
            },
        ),
        migrations.CreateModel(
            name="TypeOfReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Годовой отчет", "Годовой отчет"),
                            ("Ежемесячный отчет", "Ежемесячный отчет"),
                            ("Финансовый отчет", "Финансовый отчет"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Тип отчета",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание вида отчета")),
                ("title", models.CharField(blank=True, max_length=100, null=True, verbose_name="Новый тип отчета")),
            ],
            options={
                "verbose_name": "Тип отчета",
                "verbose_name_plural": "Типы отчетов",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=100, null=True, verbose_name="Тип отчета")),
                ("url_doc", models.FileField(blank=True, null=True, upload_to="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Время создания")),
                (
                    "type_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.typeofreport",
                        verbose_name="Тип отчета",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отчет",
                "verbose_name_plural": "Отчеты",
            },
        ),
    ]
