# Generated by Django 5.1.1 on 2024-10-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutCentre",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("about_centre", models.TextField(verbose_name="Статья")),
                ("picture", models.ImageField(blank=True, null=True, upload_to="communications/")),
                ("date_create", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "статья",
                "verbose_name_plural": "статьи",
            },
        ),
    ]
