# Generated by Django 5.1.1 on 2024-10-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Workshop",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="Заголовок_мастерские"),
                ),
                ("description_rus", models.TextField(verbose_name="Статья мастерские на русском")),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="Статья мастерские на английском"),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="agents/partners/", verbose_name="Изображение"),
                ),
                ("date_create", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Мастерские",
                "verbose_name_plural": "Мастерские",
            },
        ),
    ]
