# Generated by Django 5.1.1 on 2024-10-18 11:30


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankrequisites",
            name="bic",
            field=models.IntegerField(verbose_name="Банковский идентификационный код"),
        ),
        migrations.AlterField(
            model_name="bankrequisites",
            name="inn",
            field=models.IntegerField(verbose_name="ИНН"),
        ),
        migrations.AlterField(
            model_name="bankrequisites",
            name="kpp",
            field=models.IntegerField(verbose_name="КПП банка"),
        ),
        migrations.AlterField(
            model_name="bankrequisites",
            name="number_account",
            field=models.IntegerField(verbose_name="Расчетный счет"),
        ),
        migrations.AlterField(
            model_name="bankrequisites",
            name="ogrn_ogrnip",
            field=models.IntegerField(verbose_name="ОГРН/ОГРИП"),
        ),
        migrations.AlterField(
            model_name="bankrequisites",
            name="сorr_acc",
            field=models.IntegerField(verbose_name="Корреспондентский счет банка"),
        ),
    ]
