# Generated by Django 5.1.1 on 2024-10-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0002_alter_bankrequisites_bic_alter_bankrequisites_inn_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankrequisites",
            name="address",
            field=models.CharField(max_length=100, verbose_name="Юридический адрес"),
        ),
        migrations.AlterField(
            model_name="bankrequisites",
            name="bic",
            field=models.CharField(max_length=30, verbose_name="Банковский идентификационный код"),
        ),
        migrations.AlterField(
            model_name="bankrequisites",
            name="inn",
            field=models.CharField(max_length=30, verbose_name="ИНН"),
        ),
        migrations.AlterField(
            model_name="bankrequisites",
            name="kpp",
            field=models.CharField(max_length=30, verbose_name="КПП банка"),
        ),
        migrations.AlterField(
            model_name="bankrequisites",
            name="number_account",
            field=models.CharField(max_length=30, verbose_name="Расчетный счет"),
        ),
        migrations.AlterField(
            model_name="bankrequisites",
            name="ogrn_ogrnip",
            field=models.CharField(max_length=30, verbose_name="ОГРН/ОГРИП"),
        ),
        migrations.AlterField(
            model_name="bankrequisites",
            name="сorr_acc",
            field=models.CharField(max_length=30, verbose_name="Корреспондентский счет банка"),
        ),
    ]
