# Generated by Django 5.1.1 on 2024-10-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgressCentre",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(max_length=100, verbose_name="Описание достижения")),
                ("int_progress", models.IntegerField(verbose_name="Количественный показатель достижения")),
            ],
            options={
                "verbose_name": "Достижение",
                "verbose_name_plural": "Достижения",
            },
        ),
    ]
