# Generated by Django 5.1.1 on 2024-10-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("email", models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name="Email")),
                ("first_name", models.CharField(blank=True, max_length=50, null=True, verbose_name="Имя")),
                ("last_name", models.CharField(blank=True, max_length=75, null=True, verbose_name="Фамилия")),
                ("patronymic", models.CharField(blank=True, max_length=75, null=True, verbose_name="Отчество")),
                ("phone", models.CharField(max_length=35, verbose_name="номер телефона")),
                ("image", models.ImageField(blank=True, null=True, upload_to="user/", verbose_name="Фото")),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "user"), ("admin", "admin")],
                        default="user",
                        max_length=5,
                        verbose_name="статус пользователя",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
